on: [push]

env:
  VERCEL_ORG_ID: ${{ prj_CSBo2GMkFJ6cVeswglCP4k3GhZhM }}
  VERCEL_PROJECT_ID: ${{ CkdMFZvggo7YsYB5I1zBFH08 }}
  NEXT_PUBLIC_BASE_URL: ${{ mwu6fVH3CbclGVJvHmn6RbYl }}
  
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: |
          cd src/hack-flash
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: |
          cd src/hack-flash
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          cd src/hack-flash
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  hello_world_job:
    runs-on: ubuntu-latest
    needs: Deploy-Preview
    name: Execute Tests
    steps:
      - uses: actions/checkout@v3
      - id: hack
        uses: bistecglobal/hack-flash-action@v2.3
        with:
          base-app-url: ${{ secrets.VERCEL_APP_URL }}
          base-api-url: ${{ secrets.VERCEL_APP_URL }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
